/**
 * Copyright 2008 Fox Interative Media.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except 
 * in compliance with the License. You may obtain a copy of the License at 
 * http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in 
 * writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific 
 * language governing permissions and limitations under the License.
 */
package opensocial.Activity {
	public class Field {
		/**
		 * A string specifying the application that this activity is associated with. 
		 */		
		public static const APP_ID:String = "APP_ID";
		/**
		 * A string specifying an optional expanded version of an activity.  
		 */		
		public static const BODY:String = "BODY";
		/**
		 * An optional string ID generated by the posting application. 
		 */				
		public static const EXTERNAL_ID:String = "EXTERNAL_ID";
  		/**
  		 * A string ID that is permanently associated with this activity. 
  		 */		
  		public static const ID:String = "ID";
		/**
		 * Any photos, videos, or images that should be associated with the activity. 
		 */		
		public static const MEDIA_ITEMS:String = "MEDIA_ITEMS";
		/**
		 * A string specifying the time at which this activity took place in milliseconds since the epoch. 
		 */		
		public static const POSTED_TIME:String = "POSTED_TIME";
		/**
		 * A string specifying the URL for the stream's favicon.  
		 */		
		public static const STREAM_FAVICON_URL:String = "STREAM_FAVICON_URL";
		/**
		 * A string specifying the stream's source URL. 
		 */		
		public static const STREAM_SOURCE_URL:String = "STREAM_SOURCE_URL";
		/**
		 * A string specifing the title of the stream. 
		 */				
		public static const STREAM_TITLE:String = "STREAM_TITLE";
		/**
		 * A string specifying the stream's URL. 
		 */		
		public static const STREAM_URL:String = "STREAM_URL";
		/**
		 * A map of custom keys to values associated with this activity. 
		 */		
		public static const TEMPLATE_PARAMS:String = "TEMPLATE_PARAMS";
		/**
		 * A string specifying the primary text of an activity. 
		 */		
		public static const TITLE:String = "TITLE";
		/**
		 * A string specifying the title template message ID in the gadget spec. 
		 */		
		public static const TITLE_ID:String = "TITLE_ID";
		/**
		 * A string specifying the URL that represents this activity. 
		 */		
		public static const URL:String = "URL";
		/**
		 * The string ID of the user who this activity is for. 
		 */		
		public static const USER_ID:String = "USER_ID";
		/**
		 * A map of custom keys to values associated with this activity. 
		 */		
		public static const CUSTOM_VALUES:String = "CUSTOM_VALUES";
	}
}	