/**
 * Field - Fields in the activity
 * 
 * @author Aaron Tong
 */
package com.nextgenapp.opensocial.activity {
	public class Field {
		/**
		 * A string specifying the application that this activity is associated with. 
		 */		
		public static const APP_ID:String = "APP_ID";
		/**
		 * A string specifying an optional expanded version of an activity.  
		 */		
		public static const BODY:String = "BODY";
		/**
		 * A string specifying the body template message ID in the gadget spec. 
		 */
		public static const BODY_ID:String = "BODY_ID";
		/**
		 * An optional string ID generated by the posting application. 
		 */				
		public static const EXTERNAL_ID:String = "EXTERNAL_ID";
  		/**
  		 * A string ID that is permanently associated with this activity. 
  		 */		
  		public static const ID:String = "ID";
		/**
		 * Any photos, videos, or images that should be associated with the activity. 
		 */		
		public static const MEDIA_ITEMS:String = "MEDIA_ITEMS";
		/**
		 * A string specifying the time at which this activity took place in milliseconds since the epoch. 
		 */		
		public static const POSTED_TIME:String = "POSTED_TIME";
		/**
		 * A number between 0 and 1 representing the relative priority of this activity in relation to other activities from the same source 
		 */
		public static const PRIORITY:String = "PRIORITY";
		/**
		 * A string specifying the URL for the stream's favicon.  
		 */		
		public static const STREAM_FAVICON_URL:String = "STREAM_FAVICON_URL";
		/**
		 * A string specifying the stream's source URL. 
		 */		
		public static const STREAM_SOURCE_URL:String = "STREAM_SOURCE_URL";
		/**
		 * A string specifing the title of the stream. 
		 */				
		public static const STREAM_TITLE:String = "STREAM_TITLE";
		/**
		 * A string specifying the stream's URL. 
		 */		
		public static const STREAM_URL:String = "STREAM_URL";
		/**
		 * A map of custom keys to values associated with this activity. 
		 */		
		public static const TEMPLATE_PARAMS:String = "TEMPLATE_PARAMS";
		/**
		 * A string specifying the primary text of an activity. 
		 */		
		public static const TITLE:String = "TITLE";
		/**
		 * A string specifying the title template message ID in the gadget spec. 
		 */		
		public static const TITLE_ID:String = "TITLE_ID";
		/**
		 * A string specifying the URL that represents this activity. 
		 */		
		public static const URL:String = "URL";
		/**
		 * The string ID of the user who this activity is for. 
		 */		
		public static const USER_ID:String = "USER_ID";
	}
}	