package opensocial
{
	/**
	 * This object contains the requested server data mapped to the requested keys. 
	 * @author Joseph Estrada
	 * 
	 */	
	public class DataResponse
	{
		private var _responseItems:Object;
		private var _globalError:Boolean;
		public function DataResponse(responseItems:Object, opt_globalError:Boolean)
		{
			_responseItems = responseItems ? responseItems : {};
			_globalError = opt_globalError;
		}
		
		/**
		 * Gets the ResponseItem for the requested field. 
		 * @param key The key.
		 * @return  The requested response generated by the server.
		 * 
		 */		
		public function get(key:String):ResponseItem {
			return _responseItems[key];
		}
		
		/**
		 * Returns true if there was an error in fetching this data from the server. 
		 * @return True if there was an error; otherwise, false.
		 * 
		 */		
		public function hadError():Boolean {
			return !!_globalError;
		}
	}
}